version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
pre_build:
  commands:
    - echo Installing Maven...
    - yum install wget -y
    - wget -q https://apache.osuosl.org/maven/maven-3/3.8.3/binaries/apache-maven-3.8.3-bin.tar.gz
    - tar -xzf apache-maven-3.8.3-bin.tar.gz
    - export PATH=$PATH:/root/apache-maven-3.8.3/bin
build:
  commands:
    - echo Building the application...
    - mvn package
post_build:
  commands:
    - ls -al target
    - echo Build complete.
artifacts:
  files:
    - '/codebuild/output/src674802301/src/target/LuluPerfTest.jar'