version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Building the application...
      - mvn clean package
      - cp DslPrototype.yml target/LuluPerfTest-jar-with-dependencies.jar
      - cp ToolPrototype.yml target/LuluPerfTest-jar-with-dependencies.jar
  post_build:
    commands:
      - echo Running the application...
      - java -cp LuluPerfTest-jar-with-dependencies.jar com.lulu.main.Main
