version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Copying YAML files...
      - cp DslPrototype.yml target/classes/
      - cp ToolPrototype.yml target/classes/
  build:
    commands:
      - echo Building the application...
      - mvn clean package
  post_build:
    commands:
      - echo Running the application...
      - java -cp target/LuluPerfTest-jar-with-dependencies.jar com.lulu.main.prototype.RunnerPrototype
