version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Compiling the application...
      - mvn clean compile
  post_build:
    commands:
      - echo Running the application...
      - java -cp target/classes com.lulu.main.prototype.RunnerPrototype
